Jahia/siteSettings

src/main/java/org/jahia/modules/sitesettings/groups/ManageGroupsFlowHandler.java
https://jira.jahia.org/browse/BACKLOG-11546
Put serializable data in session : removed comparators and JCRNodeWrapper objects
=> BACKLOG-11546 : Fixed group membership handler to put serializable data

src/main/resources/css/settings/style.css
https://jira.jahia.org/browse/QA-12513
Added box-shadow + fixed header size (port missing commit from fpral)
=> QA-12513: Added box-shadow + fixed header size (port missing commit from fpral)

src/main/resources/css/settings/style.css
https://jira.jahia.org/browse/QA-12513
add missing CSS
=> QA-12513 add missing CSS

pom.xml
https://jira.jahia.org/browse/BACKLOG-11952
=> BACKLOG-11952 : Update to 7.5

src/javascript/registrations/groups/registerRoutes.js, src/javascript/registrations/users/registerRoutes.js
https://jira.jahia.org/browse/BACKLOG-11710
Add requiredPermission into routes
=> BACKLOG-11710: Add requiredPermission into routes

package.json
https://jira.jahia.org/browse/BACKLOG-12722
Update package.json
=> BACKLOG-12211 Update package.json

package.json, src/javascript/registrations/groups/registerRoutes.js, src/javascript/registrations/index.js, src/javascript/registrations/settings/registerRoutes.js, src/javascript/registrations/users/registerRoutes.js, src/main/resources/javascript/locales/en.json, src/main/resources/jnt_siteSettingsManageUsers/html/siteSettingsManageUsers.flow/search.jsp, src/main/resources/jnt_siteSettingsManageUsers/html/siteSettingsManageUsers.settingsBootstrap3GoogleMaterialStyle.flow/search.jsp, yarn.lock
https://jira.jahia.org/browse/BACKLOG-12641
Register routes in site settings
=> Backlog 12641: Register routes for site settings

src/main/resources/javascript/locales/de.json, src/main/resources/javascript/locales/fr.json
=> BACKLOG-12766: translate missing labels in French and German

src/javascript/registrations/groups/registerRoutes.js, src/javascript/registrations/settings/registerRoutes.js, src/javascript/registrations/users/registerRoutes.js
https://jira.jahia.org/browse/PROJECT-XXX
=> BACKLOG-12820: Adapted adminRoute format

src/javascript/registrations/groups/registerRoutes.js, src/javascript/registrations/settings/registerRoutes.js, src/javascript/registrations/users/registerRoutes.js
https://jira.jahia.org/browse/PROJECT-XXX
=> BACKLOG-12877: Fixed site settings urls

src/javascript/registrations/groups/registerRoutes.js, src/javascript/registrations/settings/registerRoutes.js, src/javascript/registrations/users/registerRoutes.js
…ixed icons
https://jira.jahia.org/browse/BACKLOG-12939
Updated the order the site administration panels, and added missing icons + used the correct icon for html filtering
=> BACKLOG-12939: reordering of the site administration panels 

src/main/resources/javascript/locales/de.json, src/main/resources/javascript/locales/en.json, src/main/resources/javascript/locales/fr.json
https://jira.jahia.org/browse/BACKLOG-12941
Fixed label in site settings
=> BACKLOG-12941: Fixed labels in site settings

LICENSE.txt, pom.xml, src/main/java/org/jahia/modules/sitesettings/groups/GroupModel.java, src/main/java/org/jahia/modules/sitesettings/groups/ManageGroupsFlowHandler.java, src/main/java/org/jahia/modules/sitesettings/languages/LanguagesCountAction.java, src/main/java/org/jahia/modules/sitesettings/users/UsersFlowHandler.java, src/main/java/org/jahia/modules/sitesettings/users/management/CsvFile.java, src/main/java/org/jahia/modules/sitesettings/users/management/SearchCriteria.java, src/main/java/org/jahia/modules/sitesettings/users/management/UserProperties.java, src/main/resources/META-INF/LICENSE.txt
Updated copyright year to 2020
=> Backlog-13160 - Updated copyright year to 2020

src/javascript/registrations/groups/registerRoutes.js, src/javascript/registrations/settings/registerRoutes.js, src/javascript/registrations/users/registerRoutes.js
https://jira.jahia.org/browse/BACKLOG-13213
Make site settings use adminframe so they work for system site
=> BACKLOG-13213: use adminframe for site settings

src/javascript/registrations/groups/registerRoutes.js, src/javascript/registrations/settings/registerRoutes.js, src/javascript/registrations/users/registerRoutes.js
https://jira.jahia.org/browse/PROJECT-XXX
=> BACKLOG-13362: Restore editframe for site settings

src/javascript/registrations/settings/registerRoutes.js
https://jira.jahia.org/browse/BACKLOG-13419
=> BACKLOG-13419 : hide wcag entry from site settings

pom.xml, src/main/java/org/jahia/modules/sitesettings/languages/LanguagesCountAction.java, src/main/resources/META-INF/spring/site-settings.xml
https://jira.jahia.org/browse/BACKLOG-14068
=> BACKLOG-14068: Updated version and signature, set requiredMethod

pom.xml, src/main/resources/jnt_siteSettingsManageUsers/html/siteSettingsManageUsers.settingsBootstrap3GoogleMaterialStyle.flow/editUser.jsp, src/main/resources/resources/JahiaSiteSettings_en.properties
https://jira.jahia.org/browse/BACKLOG-14907
Just a new link to the token API . There is no test if the module exists or not. Ideally this UI would be rewritten in react and works with extensions, for now the link is purely static.
=> BACKLOG-14907: Add link to edit tokens

pom.xml, src/main/resources/jnt_siteSettingsManageUsers/html/siteSettingsManageUsers.settingsBootstrap3GoogleMaterialStyle.flow/editUser.jsp, src/main/resources/resources/JahiaSiteSettings_en.properties
=> Revert "BACKLOG-14907: Add link to edit tokens"

src/main/java/org/jahia/modules/sitesettings/groups/ManageGroupsFlowHandler.java
https://jira.jahia.org/browse/QA-13370
=> QA-13370 Consider letter case searching users/groups

package.json, pom.xml, src/javascript/index.js, src/javascript/init.js, src/javascript/registrations/groups/registerRoutes.js, src/javascript/registrations/jcontent/registerRoutes.js, src/javascript/registrations/settings/registerRoutes.js, src/javascript/registrations/users/registerRoutes.js, webpack.config.js, webpack.shared.js, yarn.lock
https://jira.jahia.org/browse/BACKLOG-16220
=> BACKLOG-16220: Update dependencies, use webpack 5

pom.xml, src/main/java/org/jahia/modules/sitesettings/groups/GroupModel.java, src/main/java/org/jahia/modules/sitesettings/groups/ManageGroupsFlowHandler.java, src/main/java/org/jahia/modules/sitesettings/languages/LanguagesCountAction.java, src/main/java/org/jahia/modules/sitesettings/users/UsersFlowHandler.java, src/main/java/org/jahia/modules/sitesettings/users/management/CsvFile.java, src/main/java/org/jahia/modules/sitesettings/users/management/SearchCriteria.java, src/main/java/org/jahia/modules/sitesettings/users/management/UserProperties.java
https://jira.jahia.org/browse/QA-14203
=> QA-14203 - Update copyright year and license header

.github/dependabot.yml, .github/maven.settings.xml, .github/workflows/on-code-change.yml, .github/workflows/on-merge.yml, .github/workflows/on-release.yml, .github/workflows/on-rollback.yml, .github/workflows/schedule-sonar.yml, package.json, pom.xml, yarn.lock
=> BACKLOG-17247: Setup github workflow and refreshed yarn

src/main/resources/jnt_siteSettingsManageUsers/html/siteSettingsManageUsers.flow/editUser.jsp, src/main/resources/jnt_siteSettingsManageUsers/html/siteSettingsManageUsers.settingsBootstrap3GoogleMaterialStyle.flow/editUser.jsp
https://jira.jahia.org/browse/QA-14683
=> QA-14683: Display full group name as tooltip

pom.xml
https://jira.jahia.org/browse/TECH-1092
=> TECH-1092: Add default as dependency

src/main/java/org/jahia/modules/sitesettings/users/management/UserProperties.java
https://jira.jahia.org/browse/BACKLOG-20837
=> BACKLOG-20837: prevent xss

tests/cypress/e2e/languageSettingsUI.cy.ts, tests/cypress/page-object/languageSettings.ts
https://jira.jahia.org/browse/TECH-1230
add tests on Language settings UI
=> TECH-1230 add tests on Language settings UI

.github/workflows/nightly.yml
=> TECH-1230: Added job index to get all artifacts from the matrix

tests/cypress/e2e/languageSettingsUI.cy.ts
https://jira.jahia.org/browse/TECH-1230
Fix test to avoid flakyness
=> TECH-1230 Fix test

tests/cypress/e2e/removingLanguage.test.cy.ts
https://jira.jahia.org/browse/TECH-1221
Update removing language test to check in live
=> Tech 1221 Update removing language test to check in live

.github/workflows/nightly.yml
=> TECH-1145: Fixed nightly workflow

.github/workflows/nightly-jahiaRelease.yml, .github/workflows/nightly-jahiaSnapshot.yml
=> Split nightly tests execution and pagerduty notifications

.github/workflows/nightly-jahiaRelease.yml, .github/workflows/on-code-change.yml, .github/workflows/on-merge.yml, pom.xml
https://jira.jahia.org/browse/BACKLOG-21584
=> BACKLOG-21584 - Update parent to 8.2

.github/workflows/manual-run.yml, .github/workflows/nightly-jahiaRelease.yml, .github/workflows/nightly-jahiaSnapshot.yml, .github/workflows/on-code-change.yml, .github/workflows/on-merge.yml
https://jira.jahia.org/browse/TECH-1657
See the title
=> TECH-1657: Replace jahia-discovery with jahia-ee

.github/workflows/nightly-jahiaRelease.yml, .github/workflows/nightly-jahiaSnapshot.yml, .github/workflows/on-code-change.yml, .github/workflows/on-merge.yml
https://jira.jahia.org/browse/TECH-1488
=> TECH-1488: Re enabled tests on Jahia release

.github/workflows/manual-run.yml, .github/workflows/nightly-jahiaRelease.yml, .github/workflows/nightly-jahiaSnapshot.yml, .github/workflows/on-code-change.yml, .github/workflows/on-merge.yml, .github/workflows/on-release.yml, .github/workflows/on-rollback.yml, .github/workflows/schedule-sonar.yml
https://jira.jahia.org/browse/TECH-1639
=> TECH-1639: Updated GitHub Actions versions

src/main/resources/jnt_siteSettingsManageGroups/html/siteSettingsManageGroups.settingsBootstrap3GoogleMaterialStyle.flow/editGroup.jsp
https://jira.jahia.org/browse/QA-15178
=> QA-15178: remove useless call to fn:escapeXml causing encoding issue

package.json, src/main/java/org/jahia/modules/sitesettings/groups/ManageGroupsFlowHandler.java, tests/cypress/e2e/inheritedGroupAndUsers.test.cy.ts, tests/cypress/fixtures/groovy/deleteGroups.groovy
It is now possible to add an indirect member to a group.
> [!TIP]
> Documentation to guide the reviews: [How to do a code review](https://jahia-confluence.atlassian.net/wiki/spaces/PR/pages/2064660/How+to+do+a+code+review+-+Ref+ISSOP08.A14006)
=> feat: allow to add inderect members to a group
